spring:
  application:
    name: fileuploaderdemo
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port:  7531


fileUploader:
    image:
      save-path: E:/files/images/

